config/routes.rb
Secondkitchen::Application.routes.draw do

  resources :stock_votes do
    collection do
      get :summary
    end
    member do
      get :toggle
    end
  end

  resources :fees do
    collection do
      get :mine
    end
    member do
      get :toggle_paid
    end
  end

  resources :settings do
    collection do
      get :edit
      get :update
    end
  end

  devise_for :members
  resources :members do
    collection do
      get :home
      get :switch_user
    end
  end

  resources :orders do
    collection do
      get 'all'
      get :distribution
      get :markup
      post :fill
    end
    member do 
      get :toggle_taken
      get :toggle_paid
    end
    resources :order_details
  end

  resources :stocks
  resources :suppliers
  resources :products
  resources :services

  root :controller => "members", :action => "home"

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  has_many :order_details
  belongs_to :product
  belongs_to :supplier
  validates_presence_of :name, :cost, :quantity
  attr_accessible :name, :quantity, :cost, :markup_pct, :markup_const, :origin, :supplier_id, :product_id, :limited

  def grams(x=self.quantity,p=self.product)
    if p.unit_type == "weight"
      to_g = {"pounds" => 453.59237, "kilos" => 1000.0, "grams" => 1.0, "ounces" => 28.3495231}
      return to_g[p.units].nil? ? nil : to_g[p.units]*x
    elsif p.unit_type == "volume"
      to_ml = {"fluid ounces" => 29.5735296, "liters" => 1000.0, "cl" => 10.0}
      return (to_ml[p.units].nil? or p.density_g_per_ml.nil?)  ? nil : to_ml[p.units]*p.density_g_per_ml*x
    end
    return nil
  end

  def final_cost
    self.cost + self.cost*(self.markup_pct/100.0) + self.markup_const + self.cost*(Setting.first.global_markup_percent/100.0)
  end

  def available_items
    where("(limited = 'f') OR (limited = 't' AND quantity > 0)",:order => "name")
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_filter :require_admin, :only => ["new","edit","update","destroy","create"]

  # GET /stocks
  # GET /stocks.xml
  def index
    @stocks = Stock.all.sort{ |x,y| 
      a = x.product.nil? ? "Unknown" : x.product.category
      b = y.product.nil? ? "Unknown" : y.product.category
      a <=> b
    }

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @stocks }
    end
  end

  # GET /stocks/1
  # GET /stocks/1.xml
  def show
    @stock = Stock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @stock }
    end
  end

  # GET /stocks/new
  # GET /stocks/new.xml
  def new
    @stock = Stock.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @stock }
    end
  end

  # GET /stocks/1/edit
  def edit
    @stock = Stock.find(params[:id])
  end

  # POST /stocks
  # POST /stocks.xml
  def create
    @stock = Stock.new(params[:stock])

    respond_to do |format|
      if @stock.save
        format.html { redirect_to(@stock, :notice => 'Stock was successfully created.') }
        format.xml  { render :xml => @stock, :status => :created, :location => @stock }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @stock.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stocks/1
  # PUT /stocks/1.xml
  def update
    @stock = Stock.find(params[:id])
    respond_to do |format|
      if @stock.update_attributes(params[:stock])
        format.html { redirect_to(@stock, :notice => 'Stock was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @stock.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.xml
  def destroy
    @stock = Stock.find(params[:id])
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to(stocks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity, :size => 4 %>
  </div>
  <div class="field">
    <%= f.label :cost_per_unit %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :markup_percent %><br />
    <%= f.text_field :markup_pct %>
  </div>
  <div class="field">
    <%= f.label :markup_constant %><br />
    <%= f.text_field :markup_const %>
  </div>
  <div class="field">
    <%= f.label :origin %><br />
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :supplier %><br />
    <%= f.select :supplier_id, Supplier.all.collect{ |e| [e.name,e.id] } %>
  </div>
  <div class="field">
    <%= f.label :product %><br />
    <%= f.select :product_id, Product.all.collect{ |e| [e.name,e.id] } %>
  </div>
  <div class="field">
    <%= f.label :limited %><br />
    <%= f.check_box :limited %>
  </div>
  <div class="actions">
    <%= image_submit_tag("/images/save_button.s.png",:border=>0) %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

Note: if you modify a stock item, it will effect any order associated with
this stock item that is not yet archived. 
<br /><br />

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<h1>Current Stock</h1>

<% if current_member.admin %>
Note: If you destroy a stock item, all unarchived orders associated with that stock item will lose any parts that reference it.<br /><br />
<% end %>

<table>
  <tr>
    <th>Name</th>
    <th>Quantity</th>
    <th>Units</th>
    <th>Limited</th>
    <th>Cost per unit</th>
    <th>Markup</th>
    <th>Final Cost</th>
    <th>Value</th>
    <th>Origin</th>
    <th>Supplier</th>
    <th>Product</th>
    <th>Added On</th>
    <th>Associated Orders</th>
    <th>Average Weekly Demand</th>
    <th>Weeks Until Depleted</th>
    <th></th>
    <% if current_member.admin %>
    <th></th>
    <th></th>
    <% end %>
  </tr>

<% total_value = 0.0
   total_final_value = 0.0
   last_category = nil
   @stocks.each do |stock|
     total_value += stock.quantity*stock.cost unless stock.quantity <= 0
     total_final_value += stock.quantity*stock.final_cost unless stock.quantity <= 0
     cat = stock.product.nil? ? "Unknown" : stock.product.category
  %>
  <% if cat != last_category 
       last_category = cat
  %>
  <tr><th colspan=18 style="background: lightblue; color: black;"><%= cat.capitalize %></th></tr>
  <% end %>
  <tr>
    <td><%= stock.name %></td>
    <td style="background: <%= stock.quantity <= 0 ? 'orange' : 'white' %>;">
      <%= stock.quantity %></td>
    <td><%= stock.product.nil? ? "?" : stock.product.units %></td>
    <td><% if stock.limited %><div style="text-align: center;"><img src="/images/check_on.s.png"></div><% end %></td>
    <td><%= sprintf('$%.02f',stock.cost) %></td>
    <td><% if stock.markup_pct > 0 %><%= sprintf('%.02f%%',stock.markup_pct) %><% end %> 
        <% if stock.markup_const > 0 %>+ <%= sprintf('$%.02f',stock.markup_const) %><% end %></td>
    <td><%= sprintf('$%.02f',stock.final_cost) %></td>
    <td><% if stock.quantity > 0 %><%= sprintf('$%.02f',stock.quantity*stock.final_cost) %><% end %></td>
    <td><%= stock.origin %></td>
    <td><%= stock.supplier.nil? ? "?" : stock.supplier.name %></td>
    <td><%= stock.product.nil? ? "?" : stock.product.name %></td>
    <td><%= stock.created_at.strftime('%Y-%m-%d') %></td>
    <td><%= stock.order_details.length %>
    <td><% weeks = {}
           stock.order_details.each do |od|
             w = od.updated_at.strftime('%U')
             weeks[w] = 0.0 if weeks[w].nil?
             weeks[w] += od.quantity
           end
           k = weeks.length == 0 ? 0 : weeks.values.sum/weeks.length
         %><% unless k == 0 %><%= sprintf('%.01f',k) %><% else %>Not sure yet.<% end %>
    <td style="background: <%= k > 0 and stock.quantity/k < 2 ? "yellow" : "white" %>;"><% unless k == 0 %><%= (stock.quantity/k).floor %><% else %> Not sure yet. <% end %>
    <td><%= link_to image_tag("/images/view_button.s.png",:border=>0), stock %></td>
    <% if current_member.admin %>
    <td><%= link_to image_tag("/images/edit_button.s.png",:border=>0), edit_stock_path(stock) %></td>
    <td><%= link_to image_tag("/images/nix_button.s.png",:border=>0), stock, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
Total capital invested in stock: <%= sprintf('$%.02f',total_value) %><br>
Total redeemable value if sold: <%= sprintf('$%.02f',total_final_value) %><br>
Estimated Profit: <%= sprintf('$%.02f',total_final_value-total_value) %> with margin <%= sprintf('%.02f',100.0*(total_final_value-total_value)/total_final_value) %>%

app/views/stocks/new.html.erb
<h1>New Stock Item</h1>

<%= render 'form' %>

<%= link_to image_tag("/images/back_button.s.png",:border=>0), stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @stock.name %>
</p>

<p>
  <b>Quantity:</b>
  <%= @stock.quantity %>
</p>

<p>
  <b>Cost:</b>
  <%= @stock.cost %>
</p>

<p>
  <b>Origin:</b>
  <%= @stock.origin %>
</p>

<% unless @stock.supplier.nil? %>
<p>
  <b>Supplier:</b>
  <%= @stock.supplier.name %>
</p>
<% end %>

<% unless @stock.product.nil? %>
<p>
  <b>Product Type:</b>
  <%= @stock.product.name %>
</p>
<% end %>

<p>
  <b>Limited Item:</b>
  <%= @stock.limited ? "Yes" : "No" %>
</p>

<%= link_to image_tag("/images/back_button.s.png",:border=>0), stocks_path %>

<%= link_to image_tag("/images/edit_button.s.png",:border=>0), edit_stock_path(@stock) %>