config/routes.rb
Secondkitchen::Application.routes.draw do

  resources :stock_votes do
    collection do
      get :summary
    end
    member do
      get :toggle
    end
  end

  resources :fees do
    collection do
      get :mine
    end
    member do
      get :toggle_paid
    end
  end

  resources :settings do
    collection do
      get :edit
      get :update
    end
  end

  devise_for :members
  resources :members do
    collection do
      get :home
      get :switch_user
    end
  end

  resources :orders do
    collection do
      get 'all'
      get :distribution
      get :markup
      post :fill
    end
    member do 
      get :toggle_taken
      get :toggle_paid
    end
    resources :order_details
  end

  resources :stocks
  resources :suppliers
  resources :products
  resources :services

  root :controller => "members", :action => "home"

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :stocks
  has_many :order_details
  attr_accessible :name, :category, :units, :density_g_per_ml, :servings_per_unit

  Units = ["pounds","ounces","fluid ounces","grams","ml","cl","liters","dozen","packages","boxes","units","cans","jars"]

  def unit_type
    if ["pounds","ounces","grams"].include? self.units
      "weight"
    elsif ["fluid ounces","milliliters","centiliters","liters"].include? self.units
      "volume"
    elsif ["dozen","packages","boxes","units","cans","jars"].include? self.units
      "count"
    else
      nil
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :require_admin

  # GET /products
  # GET /products.xml
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.xml
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => 'Product was successfully created.') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.select :category, ["grains","meat","eggs","dairy","sweeteners","oil","produce","miscellany","beans","nuts","dried fruit","spices","seeds","tea","canned goods"] %>
  </div>
  <div class="field">
    <%= f.label :units %><br />
    <%= f.select :units, Product::Units %>
  </div>
  <div class="field">
    <%= f.label :density %><br />
    <%= f.text_field :density_g_per_ml %>
  </div>
  <div class="field">
    <%= f.label :servings_per_unit %><br />
    <%= f.text_field :servings_per_unit %>
  </div>

  <div class="actions">
    <%= image_submit_tag("/images/save_button.s.png",:border=>0) %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to image_tag("/images/back_button.s.png",:border=>0), products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Units</th>
    <th>Density (g/ml)</th>
    <th>Servings/unit</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.category %></td>
    <td><%= product.units %> (<%= product.unit_type %>)</td>
    <td><%= product.density_g_per_ml %></td>
    <td><%= product.servings_per_unit %></td>
    <td><%= link_to image_tag("/images/view_button.s.png",:border=>0), product %></td>
    <td><%= link_to image_tag("/images/edit_button.s.png",:border=>0), edit_product_path(product) %></td>
    <td><%= link_to image_tag("/images/nix_button.s.png",:border=>0), product, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to image_tag("/images/back_button.s.png",:border=>0), products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Category:</b>
  <%= @product.category %>
</p>

<p>
  <b>Units:</b>
  <%= @product.units %>
</p>

<p>
  <b>Density (g/ml):</b>
  <%= @product.density_g_per_ml %>
</p>

<p>
  <b>Servings/unit:</b>
  <%= @product.servings_per_unit %>
</p>

<table>
<tr><th>Name<th>Total Quantity Ordered
<% 
by_member = {}
OrderDetail.where(:stock_id => Stock.find_all_by_product_id(@product.id).collect{ |s| s.id }).each{ |od| 
  mib = od.order.member.id
  by_member[mib] = 0.0 if by_member[mib].nil?
  by_member[mib] += od.quantity
}
by_member.sort{ |a,b| b[1] <=> a[1] }.each{ |mib,q|
%>
<tr><td><%= Member.find(mib).name %><td><%= q %>
<% } %>
</table>
<br>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>