config/routes.rb
Secondkitchen::Application.routes.draw do

  resources :stock_votes do
    collection do
      get :summary
    end
    member do
      get :toggle
    end
  end

  resources :fees do
    collection do
      get :mine
    end
    member do
      get :toggle_paid
    end
  end

  resources :settings do
    collection do
      get :edit
      get :update
    end
  end

  devise_for :members
  resources :members do
    collection do
      get :home
      get :switch_user
    end
  end

  resources :orders do
    collection do
      get 'all'
      get :distribution
      get :markup
      post :fill
    end
    member do 
      get :toggle_taken
      get :toggle_paid
    end
    resources :order_details
  end

  resources :stocks
  resources :suppliers
  resources :products
  resources :services

  root :controller => "members", :action => "home"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Second Kitchen</title>
  <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.5.1/build/cssreset/cssreset-min.css">
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag :application %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %>
</head>
<body>

<div class="container">
<div class="navigation">
<div id="cssmenu"><ul>
<% if !current_member %>
<% else %>
  <li><%= link_to "Home", :controller => "members", :action => "show", :id => current_member %>
  <% if current_member.admin %>
    <li><%= link_to "Orders", orders_path %>
     <ul>
       <li><%= link_to "Show All", :controller => "orders", :all => 1 %>
       <li><%= link_to "Distribution", :controller => "orders", :action => "distribution" %>
       <li><%= link_to "Markup Report", :controller => "orders", :action => "markup" %>
       <li><%= link_to "New Order", :controller => "orders", :action => "new" %>
     </ul>
    <li><%= link_to "Members", members_path %>
    <li><%= link_to "Stock", stocks_path %>
     <ul>
       <li><%= link_to "New Stock Item", :controller => "stocks", :action => "new" %>
       <li><%= link_to "New Product", :controller => "products", :action => "new" %>
       <li><%= link_to "New Supplier", :controller => "suppliers", :action => "new" %>
       <li><%= link_to "List Suppliers", suppliers_path %>
       <li><%= link_to "List Products", products_path %>
       <li><%= link_to "Your Wishlist", stock_votes_path %>
       <li><%= link_to "Wishlist Summary", summary_stock_votes_path %>
     </ul>
    <li><%= link_to "Workshare", services_path %>
     <ul>
       <li><%= link_to "Add Observed Work", :controller => "services", :action => "new" %>
     </ul>
    <li><%= link_to "Fees", fees_path %>
     <ul>
      <li><%= link_to 'New Fee', new_fee_path %>
     </ul>
    <li><%= link_to "Admin Stuff", edit_settings_path %>
  <% else %>
  <li><%= link_to "My Orders", orders_path %>
   <ul>
     <li><%= link_to "Past Orders", :controller => "orders", :all => 1 %>
     <li><%= link_to "Distribution", :controller => "orders", :action => "distribution" %>
     <li><%= link_to "View Stock", stocks_path %>
     <li><%= link_to "Wishlist", stock_votes_path %>
     <% unless current_member.disabled %>
     <li><%= link_to "New Order", :controller => "orders", :action => "new" %>
     <% end %>
   </ul>
  <li><%= link_to "Members List", members_path %>
  <% end %>
  <li><%= link_to "Logout", "/members/sign_out" %>
<% end %>
</ul>
</div>
</div>

  <div class="header">
    <div>
      <h2 id="title">The Second Kitchen</h2>
    </div>
    <%= link_to root_path do image_tag("/images/logo.png",:class => "logo_image") end %>
  </div>

  <div class="wrap">
    <% if notice %>
     <div class="notice"><%= notice %></div>
    <% end %>
    <% if alert %>
     <div class="alert"><%= alert %></div>
    <% end %>
    <%= yield %>
  </div>

  <div class="footer">
    <p>Copyright © <a href="http://www.thesecondkitchen.org">The Second Kitchen</a> <%= Time.now.year %></p>
  </div>

</div>

</body>
</html>