config/routes.rb
Secondkitchen::Application.routes.draw do

  resources :stock_votes do
    collection do
      get :summary
    end
    member do
      get :toggle
    end
  end

  resources :fees do
    collection do
      get :mine
    end
    member do
      get :toggle_paid
    end
  end

  resources :settings do
    collection do
      get :edit
      get :update
    end
  end

  devise_for :members
  resources :members do
    collection do
      get :home
      get :switch_user
    end
  end

  resources :orders do
    collection do
      get 'all'
      get :distribution
      get :markup
      post :fill
    end
    member do 
      get :toggle_taken
      get :toggle_paid
    end
    resources :order_details
  end

  resources :stocks
  resources :suppliers
  resources :products
  resources :services

  root :controller => "members", :action => "home"

end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name1, 
                  :name2, :name3, :extra_emails, :phone, :disabled, :disabled_reason, 
                  :admin, :joined_on, :service_group

  has_many :orders, :dependent => :destroy
  validates_presence_of :name1, :email
  validates_uniqueness_of :email

  ServiceStartDate = Time.local(2013,01,01)
  HoursPerMonth = 2.0
  
  def name
    [name1,name2,name3].collect{ |e| e.nil? or e.strip == "" ? nil : e }.compact.join(", ")
  end

  def service_total
    # would be more efficient to do this select in the db...
    Service.find_all_by_member_id(self.id).collect{ |e| e.created_at >= ServiceStartDate ? e.hours : nil }.compact.sum
  end

  def start_date
    self.joined_on.nil? ? self.created_at.to_date : self.joined_on
  end
 
  def service_per_week
    (self.service_total/(self.days_since_service_start/7.0))
  end

  def service_per_month
    self.months_since_service_start == 0 ? 0.0 : self.service_total/self.months_since_service_start
  end

  def days_as_member
    ((Time.now - self.start_date.to_time)/(2400*24)).ceil
  end

  class Month<Date
    def next
      self >> 1
    end
    def prior
      self << 1
    end
  end

  def consecutive_months_under_service
    cur = Month.new(Time.now.year,Time.now.month)
    #first = Month.new(self.start_date.year,self.start_date.month)
    first = Month.new(ServiceStartDate.year,ServiceStartDate.month)
    thresh = Setting.first.workshare_hours_per_month
    return 0 if thresh.nil?
    # start at -1 because we're considering the current month too
    n = -1 
    while cur >= first
      sum = 0
      Service.where("member_id=? AND extract(year from did_at)=? AND extract(month from did_at)=?",self.id,cur.year,cur.month).collect{ |s| 
        sum += s.hours unless s.hours.nil? 
      }
      if sum < thresh
        n += 1
      else
        break
      end
      cur = cur.prior
    end
    return n
  end

  # hack!
  def days_since_service_start
    ((Time.now - ServiceStartDate)/(2400*24)).round
  end

  def months_since_service_start
    y1 = ServiceStartDate.year
    m1 = ServiceStartDate.month
    y2 = Time.now.year
    m2 = Time.now.month
    (y2*12+m2)-(y1*12+m1)
  end

  def service_balance
    self.months_since_service_start*HoursPerMonth - self.service_total
  end


end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_filter :require_admin, :only => [:new, :create]
  before_filter :require_owner, :only => [:edit, :update]

  def require_owner
    unless current_member and current_member.admin or params[:id] == current_member.id
      store_location
      flash[:notice] = "Hey, that's not yours!"
      redirect_to account_path
    end
  end

  # GET /members
  # GET /members.xml
  def index
    @members = Member.all(:order => :name1)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @members }
    end
  end

  def home
    show
  end

  # GET /members/1
  # GET /members/1.xml
  def show
    @member = params[:id].nil? ? current_member : Member.find(params[:id])
    unless current_member.admin or @member.id == current_member.id
      store_location
      flash[:notice] = "Hey, that's not yours!"
      redirect_to account_path
    else
      respond_to do |format|
        format.html { render :show } # show.html.erb
        format.xml  { render :xml => @member }
      end
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # PUT /members/1
  # PUT /members/1.xml
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to(@member, :notice => 'Member was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @member.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.xml
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to(members_url) }
      format.xml  { head :ok }
    end
  end

  # switch to a particular user
  def switch_user
    m = Member.find(params[:member_id].to_i)
    unless current_member.admin
      flash[:notice] = "You're not authorized to switch to that user!"
      redirect_to(root_path)
      return
    end
    sign_out(current_member)
    sign_in(m)
    flash[:notice] = "Successfully switched to user #{current_member.name}."
    home
  end

end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <div class="field">
    <%= f.label :name1 %><br />
    <%= f.text_field :name1 %>
  </div>
  <div class="field">
    <%= f.label :name2 %><br />
    <%= f.text_field :name2 %>
  </div>
  <div class="field">
    <%= f.label :name3 %><br />
    <%= f.text_field :name3 %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :extra_emails %><br />
    <%= f.text_field :extra_emails %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <% if current_member.admin %>
    <div class="field">
      <%= f.label :joined_on %><br />
      <%= f.text_field :joined_on, :class => 'datepicker' %>
    </div>
    <div class="field">
      <%= f.label :workshare_group %><br />
      <%= f.text_field :service_group %>
    </div>
    <div class="field">
      <%= f.label :disabled %><br />
      <%= f.check_box :disabled %>
    </div>
    <div class="field">
      <%= f.label :disabled_reason %><br />
      <%= f.text_area :disabled_reason, :size => "30x3" %>
    </div>
    <div class="field">
      <%= f.label :admin %><br />
      <%= f.check_box :admin %>
    </div>

  <% end %>

  <div class="actions">
    <%= image_submit_tag("/images/save_button.s.png",:border=>0) %>
  </div>
<% end %>

<script type="text/javascript">
$( ".datepicker" ).datepicker({ dateFormat: 'yy-mm-dd' });
</script>

app/views/members/edit.html.erb
<h1>Editing Member <%= @member.id %></h1>

<%= render 'form' %>

<%= link_to image_tag("/images/back_button.s.png",:border=>0), members_path %>

app/views/members/index.html.erb
<h1>Members List</h1>

<table>
  <tr>
    <th>
    <th>Name(s)</th>
    <th>Email(s)</th>
    <th>Phone</th>
    <th>Member Since</th>
    <% if current_member.admin %>
    <th>Orders</th>
    <th>Service</th>
    <th></th>
    <% end %>
  </tr>

<%
 i = 1
 @members.each do |member| 
  row_bgcolor = nil
  if member.disabled
    row_bgcolor = "lightgrey"
  elsif member.admin
    row_bgcolor = "lightblue"
  end
 %>
  <tr <%= "style=\"background: #{row_bgcolor};\"".html_safe unless row_bgcolor.nil? %>>
    <th><%= i %>
    <td><%= member.name %></td>
    <td><%= member.email %><br><%= member.extra_emails.split(/[,\s]+/).join("<br>").html_safe unless member.extra_emails.nil? %></td>
    <td><%= member.phone %></td>

    <td><%= member.created_at.strftime('%Y-%m-%d') %> (<%= member.days_as_member %> days)</td>
    <% if current_member.admin %>
    <td><%= member.orders.length %>
    <td><% n = member.consecutive_months_under_service %>
        <%= n <= 0 ? "Ok" : "#{n} months under-service" %>
    <td><%= link_to image_tag("/images/view_button.s.png",:border=>0), member %><br>
        <%= link_to image_tag("/images/edit_button.s.png",:border=>0), edit_member_path(member) %><br>
        <%= link_to image_tag("/images/nix_button.s.png",:border=>0), member, :confirm => 'Are you sure?', :method => :delete %><br>
    <% end %>
  </tr>
<% 
i += 1
end %>
</table>
<br><br>
Key: <span style="background: lightgrey;">Account Disabled</span>
<span style="background: lightblue;">Admin</span>

app/views/members/show.html.erb
<% if @member.disabled %>
<div style="background: maroon; border: 1px solid red; color: white; padding: 1em;">
Account is disabled. You will not be able to place an order until your account is re-enabled.
<br><br>
Reason: <%= @member.disabled_reason %>
</div><br>
<% end %>

<h1><%= @member.id == current_member.id ? 'Welcome!' : "Member " + @member.id.to_s %></h1>

<p>
  <b>Name(s):</b>
  <%= @member.name %>
</p>

<p>
  <b>Primary Email:</b>
  <%= @member.email %>
</p>

<p>
  <b>Other Emails:</b>
  <%= @member.extra_emails %>
</p>

<p>
  <b>Phone Number:</b>
  <%= @member.phone %>
</p>
<br><br>
<% 
product_stats = {}
product_sort = {}
week_stats = {}
Order.find_all_by_member_id(@member.id).each do |o|
  w = o.updated_at.strftime('%U') 
  week_stats[w] = {:n => 0, :cost => 0.0} if week_stats[w].nil?
  week_stats[w][:n] += 1
  week_stats[w][:cost] += o.cost
  o.order_details.each{ |od|
    next if od.stock.nil? or (o.archived and od.archived_product.nil?)
    pid = o.archived ? od.archived_product.id : od.stock.product.id
    product_stats[pid] = 0.0 if product_stats[pid].nil?
    product_stats[pid] += od.quantity
    product_sort[pid] = 0.0 if product_sort[pid].nil?
    g = o.archived ? od.stock.grams(od.quantity,od.archived_product) : od.stock.grams(od.quantity,od.stock.product)
    product_sort[pid] += g unless g.nil?
  }
end 
psort = product_stats.sort{ |a,b| product_sort[b[0]] <=> product_sort[a[0]] }
if week_stats.length > 0
%>
You have made <%= week_stats.collect{ |k,v| v[:n] }.sum %> orders, and have been a member for <%= @member.days_as_member %> days.
<br><br>
On average, you spend <%= sprintf('$%.02f',week_stats.collect{ |k,v| v[:cost] }.sum/(@member.days_as_member/30.0)) %> dollars a month at the co-op. And, you have spent <%= sprintf('$%.02f',week_stats.collect{ |k,v| v[:cost] }.sum) %> total.
<br><br>
Here are some statistics on what you've ordered:<br><br>
<table>
<tr><th>Product<th>Total Purchased<th>Average per Week</tr>
<% psort.each do |k,v| 
     p = Product.find_by_id(k) %>
<tr><td><%= p.name %><td><%= v.round %> <%= p.units %> <% unless product_sort[p.id] == 0.0 %>(<%= product_sort[p.id].round %> g)<% end %>
    <td><%= sprintf('%.02f',v/(@member.days_as_member/7.0)) %> <%= p.units %>
<% end %>
</table>
<% else %>
You haven't ordered anything. That's awfully boring...
<% end %>
<br><br>
You have worked <%= sprintf("%.02f",@member.service_total) %> hours for the co-op since <%= Member::ServiceStartDate.strftime('%m/%d/%Y') %>, which works out to <%= sprintf("%.02f",@member.service_per_month) %> hours per month. 
<br><br>
<%= link_to image_tag("/images/back_button.s.png",:border=>0), members_path %>
<% if current_member.admin or @member.id == current_member.id %>
<%= link_to image_tag("/images/edit_button.s.png",:border=>0), edit_member_path(@member) %>
<% end %>